- package-ecosystem: "cargo"
  directory: "/"
  commit-message:
    prefix: "cargo"
  labels: [ 'chore' ]
  assignees:
  - "Harvester57"
  schedule:
    interval: "cron"
    cronjob: "0 7 * * *"
    timezone: "Europe/Paris"
  groups:
    actions-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
