- package-ecosystem: "gomod"
  directory: "/"
  commit-message:
    prefix: "go"
  labels: [ 'chore' ]
  assignees:
  - "Harvester57"
  schedule:
    interval: "cron"
    cronjob: "0 7 * * *"
    timezone: "Europe/Paris"
  groups:
    go-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
  allow:
  - dependency-type: all
