- package-ecosystem: "docker"
  directory: "/"
  commit-message:
    prefix: "docker"
  labels: [ 'chore ' ]
  assignees:
  - "Harvester57"
  schedule:
    interval: "cron"
    cronjob: "0 7 * * *"
    timezone: "Europe/Paris"
  groups:
    docker-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
